name: 'precision_cagr'
version: '1.0.0'
config-version: 2

profile: 'precision_cagr'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ dbt.run_query(\"CREATE TABLE IF NOT EXISTS PRECISION.ANALYTICS_RAW.CPI_CONFIG (config_key VARCHAR, default_value VARCHAR, override_value VARCHAR, override_until_date DATE)\") }}"

seeds:
  precision_cagr:
    schema: RAW
