version: 2

sources:
  - name: raw
    database: "{% if var('env_name', '') != '' %}PRECISION_{{ var('env_name') }}{% else %}PRECISION{% endif %}"
    schema: RAW
    tables:
      - name: properties
      - name: leases
      - name: financials
